# do not use "latest" here, if you want this to work in the future
image: docker:18

stages:
  - build

services:
  - docker:dind

before_script:
  # docker login asks for the password to be passed through stdin for security
  # we use $CI_JOB_TOKEN here which is a special token provided by GitLab
  - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY

Build latest:
  stage: build
  only:
    - tags
  script:
    # fetches the latest image (not failing if image is not found)
    - docker pull $CI_REGISTRY_IMAGE/app:latest || true
    # builds the project, passing vcs vars for LABEL
    # notice the cache-from, which is going to use the image we just pulled locally
    # the built image is tagged locally with the commit SHA, and then pushed to
    # the GitLab registry
    - >
      docker build
      --pull
      --build-arg VCS_REF=latest
      --build-arg VCS_URL=$CI_PROJECT_URL
      --cache-from $CI_REGISTRY_IMAGE:latest
      --tag $CI_REGISTRY_IMAGE/app:latest
      --tag $CI_REGISTRY_IMAGE/app:$CI_COMMIT_REF_NAME
      .
    - docker push $CI_REGISTRY_IMAGE/app:latest
    - docker push $CI_REGISTRY_IMAGE/app:$CI_COMMIT_REF_NAME

Build staging:
  stage: build
  only:
    - staging
  script:
    # fetches the latest image (not failing if image is not found)
    # socker pull $CI_REGISTRY_IMAGE/app:$CI_COMMIT_REF_NAME || true
    # builds the project, passing vcs vars for LABEL
    # notice the cache-from, which is going to use the image we just pulled locally
    # the built image is tagged locally with the commit SHA, and then pushed to
    # the GitLab registry
    - >
      docker build
      --pull
      --build-arg VCS_REF=staging
      --build-arg VCS_URL=$CI_PROJECT_URL
      --cache-from $CI_REGISTRY_IMAGE/app:$CI_COMMIT_REF_NAME
      --tag $CI_REGISTRY_IMAGE/app:$CI_COMMIT_REF_NAME
      .
    - docker push $CI_REGISTRY_IMAGE/app:$CI_COMMIT_REF_NAME
