version: "3"

## Setup Node.js container
services:
  server:
    build: ./server
    image: registry.gitlab.com/garneau-dev/sugoi/custom-proofs/server
    restart: always
    ports:
      - "3000:3000"
    volumes:
      # - ./certs:/certs
      # - ./logs/custom-proofs/apache2:/var/log/apache2
      - ./server:/usr/src/app
    depends_on:
      - mongo
    links:
      - mongo
  mongo:
    container_name: mongo
    restart: always
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db

volumes:
  mongodbdata:
