# NEED TO FIX THIS

version: "3"

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: ${LGS_HOST_SUBNET}/24

services:
  logger:
    restart: always
    image: ${LGS_LOGGER_IMAGE}
    user: root
    volumes:
      - /data/logs/${LGS_HOST_APP_DIR}:/logs
      - /etc/pki/tls/certs/COMODORSADomainValidationSecureServerCA.crt:/certificate.crt
      - ./filebeat-data:/usr/share/filebeat/data/
    environment:
      - LGS_ENV=${LGS_ENV}

  server:
    restart: always
    image: ${LGS_DOCKER_IMAGE1}
    #depends_on:
    #  - mySQL
    ports:
      - "8104:80"
      - "8448:443"
    volumes:
      - ./certs:/certs
      - /data/logs/${LGS_HOST_APP_DIR}/apache2:/var/log/apache2
